"""ADB server endpoint, generation, lifecycle, failure, and availability contracts."""

from adb._lifecycle import (
    AcquireBlocked,
    AcquireCommitted,
    AcquireExisting,
    AcquireFailed,
    AcquireSuperseded,
    EndpointAccess,
    LifecycleSnapshot,
    ReleaseAccessDetached,
    ReleaseAcquisitionRevoked,
    ReleaseGenerationMismatch,
    ReleaseInactive,
)
from adb.server.lifecycle import (
    AdbServerAccess,
    AdbServerAcquireOutcome,
    AdbServerLifecycle,
    AdbServerLifecycleConsistencyError,
    AdbServerLifecycleError,
    AdbServerLifecycleFactory,
    AdbServerReleaseOutcome,
)
from adb.server.failure import (
    AdbServerConnectionFailure,
    AdbServerFailure,
    AdbServerLaunchFailure,
    AdbServerLifecycleFailure,
    AdbServerLivenessFailure,
    AdbServerProcessExitedFailure,
    AdbServerProtocolFailure,
    AdbServerRequestFailure,
    AdbServerServiceFailure,
    AdbServerTimeoutFailure,
)
from adb.server.generation import AdbServerGeneration, AdbServerGenerationIssuer
from adb.server.endpoint import AdbServerEndpoint
from adb.server.state import AdbServerState, AdbServerStateView

__all__ = [
    "AcquireBlocked",
    "AcquireCommitted",
    "AcquireExisting",
    "AcquireFailed",
    "AcquireSuperseded",
    "AdbServerAccess",
    "AdbServerAcquireOutcome",
    "AdbServerConnectionFailure",
    "AdbServerEndpoint",
    "AdbServerFailure",
    "AdbServerGeneration",
    "AdbServerGenerationIssuer",
    "AdbServerLaunchFailure",
    "AdbServerLifecycle",
    "AdbServerLifecycleConsistencyError",
    "AdbServerLifecycleError",
    "AdbServerLifecycleFactory",
    "AdbServerLifecycleFailure",
    "AdbServerLivenessFailure",
    "AdbServerProcessExitedFailure",
    "AdbServerProtocolFailure",
    "AdbServerReleaseOutcome",
    "AdbServerRequestFailure",
    "AdbServerServiceFailure",
    "AdbServerState",
    "AdbServerStateView",
    "AdbServerTimeoutFailure",
    "EndpointAccess",
    "LifecycleSnapshot",
    "ReleaseAccessDetached",
    "ReleaseAcquisitionRevoked",
    "ReleaseGenerationMismatch",
    "ReleaseInactive",
]
