"""ADB server endpoint, generation, lifecycle, failure, and availability contracts."""

from adb.server.availability import AdbServerUnavailableError
from adb.server.lifecycle import (
    AdbServerActivated,
    AdbServerLifecycle,
    AdbServerAcquisition,
    AdbServerAcquireBlocked,
    AdbServerAcquireCommitted,
    AdbServerAcquireFailed,
    AdbServerAcquireSuperseded,
    AdbServerAcquireExisting,
    AdbServerAcquireOutcome,
    AdbServerLifecycleEventPublisherBinding,
    AdbServerLifecycleFactory,
    AdbServerReleaseApplied,
    AdbServerReleaseInactive,
    AdbServerReleaseGenerationMismatch,
    AdbServerReleaseOutcome,
    AdbServerBootstrapError,
    AdbServerDeactivated,
    AdbServerLifecycleConsistencyError,
    AdbServerLifecycleError,
)
from adb.server.failure import (
    AdbServerConnectionFailure,
    AdbServerFailure,
    AdbServerLaunchFailure,
    AdbServerLifecycleFailure,
    AdbServerLivenessFailure,
    AdbServerProcessExitedFailure,
    AdbServerProtocolFailure,
    AdbServerRequestFailure,
    AdbServerServiceFailure,
    AdbServerTimeoutFailure,
)
from adb.server.generation import AdbServerGeneration, AdbServerGenerationIssuer
from adb.server.endpoint import AdbServerEndpoint
from adb.server.state import AdbServerState, AdbServerStateView

__all__ = [
    "AdbServerActivated",
    "AdbServerLifecycle",
    "AdbServerAcquisition",
    "AdbServerAcquireBlocked",
    "AdbServerAcquireCommitted",
    "AdbServerAcquireFailed",
    "AdbServerAcquireSuperseded",
    "AdbServerAcquireExisting",
    "AdbServerAcquireOutcome",
    "AdbServerLifecycleEventPublisherBinding",
    "AdbServerLifecycleFactory",
    "AdbServerReleaseApplied",
    "AdbServerReleaseInactive",
    "AdbServerReleaseGenerationMismatch",
    "AdbServerReleaseOutcome",
    "AdbServerBootstrapError",
    "AdbServerConnectionFailure",
    "AdbServerDeactivated",
    "AdbServerEndpoint",
    "AdbServerFailure",
    "AdbServerGeneration",
    "AdbServerGenerationIssuer",
    "AdbServerLaunchFailure",
    "AdbServerLifecycleConsistencyError",
    "AdbServerLifecycleError",
    "AdbServerLifecycleFailure",
    "AdbServerLivenessFailure",
    "AdbServerProcessExitedFailure",
    "AdbServerProtocolFailure",
    "AdbServerRequestFailure",
    "AdbServerServiceFailure",
    "AdbServerState",
    "AdbServerStateView",
    "AdbServerTimeoutFailure",
    "AdbServerUnavailableError",
]
