"""High-level host-side ADB domain and runtime API.

Low-level lifecycle, generation, protocol, and adapter APIs live in their
respective subpackages instead of being re-exported from the package root.
"""

from adb.errors import (
    AdbError,
    AdbProtocolError,
    AdbRemoteCommandError,
    AdbServerConnectionError,
    AdbServiceError,
    AdbTimeoutError,
    AdbTransportAmbiguousError,
    AdbTransportNotFoundError,
    AdbTransportSelectionError,
    AdbTransportUnavailableError,
)
from adb.runtime import (
    AdbServerAvailabilityConflict,
    AdbServerAvailabilityFailed,
    AdbServerAvailabilityPolicy,
    AdbServerAvailabilityResult,
    AdbServerAvailabilitySupervisor,
    AdbServerAvailable,
    AdbServerActivateAlreadyActive,
    AdbServerActivateConflict,
    AdbServerActivateFailed,
    AdbServerActivateReleaseRequired,
    AdbServerActivateResult,
    AdbServerActivateSucceeded,
    AdbServerDeactivateAlreadyIdle,
    AdbServerDeactivateResult,
    AdbServerDeactivateSucceeded,
    AdbServerMutationFacade,
    AdbServerRuntime,
    bootstrap_adb_server_runtime,
)
from adb.server import (
    AdbServerCapability,
    AdbServerPhase,
    AdbServerRequest,
    AdbServerSnapshot,
    AdbServerSnapshotReader,
)
from adb.transport import (
    AdbDeviceSerial,
    AdbObservedTransportKind,
    AdbObservedTransportState,
    AdbTransport,
    AdbTransportById,
    AdbTransportBySerial,
    AdbTransportFeatures,
    AdbTransportFeaturesReader,
    AdbTransportId,
    AdbTransportSelector,
    AdbTransportState,
)
from adb.transport_list import (
    AdbTransportList,
    AdbTransportListReader,
    AdbTransportListState,
    AdbTransportListStateAuthority,
    AdbTransportListStateStore,
    AdbTransportListStateView,
    AdbTransportListStateWriter,
)

__all__ = [
    "AdbServerAvailabilityConflict",
    "AdbServerAvailabilityFailed",
    "AdbServerAvailabilityPolicy",
    "AdbServerAvailabilityResult",
    "AdbServerAvailabilitySupervisor",
    "AdbServerAvailable",
    "AdbDeviceSerial",
    "AdbError",
    "AdbObservedTransportKind",
    "AdbObservedTransportState",
    "AdbProtocolError",
    "AdbRemoteCommandError",
    "AdbServerActivateAlreadyActive",
    "AdbServerActivateConflict",
    "AdbServerActivateFailed",
    "AdbServerActivateReleaseRequired",
    "AdbServerActivateResult",
    "AdbServerActivateSucceeded",
    "AdbServerCapability",
    "AdbServerConnectionError",
    "AdbServerDeactivateAlreadyIdle",
    "AdbServerDeactivateResult",
    "AdbServerDeactivateSucceeded",
    "AdbServerMutationFacade",
    "AdbServerPhase",
    "AdbServerRequest",
    "AdbServerRuntime",
    "AdbServerSnapshot",
    "AdbServerSnapshotReader",
    "AdbServiceError",
    "AdbTimeoutError",
    "AdbTransport",
    "AdbTransportAmbiguousError",
    "AdbTransportById",
    "AdbTransportBySerial",
    "AdbTransportFeatures",
    "AdbTransportFeaturesReader",
    "AdbTransportId",
    "AdbTransportList",
    "AdbTransportListReader",
    "AdbTransportListState",
    "AdbTransportListStateAuthority",
    "AdbTransportListStateStore",
    "AdbTransportListStateView",
    "AdbTransportListStateWriter",
    "AdbTransportNotFoundError",
    "AdbTransportSelectionError",
    "AdbTransportSelector",
    "AdbTransportState",
    "AdbTransportUnavailableError",
    "bootstrap_adb_server_runtime",
]
